# fly.toml file generated for solitary-smoke-3338 on 2022-08-22T14:38:49+02:00

app = "solitary-smoke-3338"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
